# Classificando os alunos como alunos desistentes e não desistentes

## Importando os aquivos para trabalho

In [0]:
!unzip -q '/content/drive/My Drive/PBICT-UEA-2019 2020/arquivos_de_mineracao/codebench.zip'

> Coisas para fazer antes de classificar

    * Verificar se o aluno possui arquivo de notas;
    * Verificar quantos alunos não possuem os arquivos com as informações das notas;
    * Verificar qual são as notas dos alunos no arquivo de notas;

In [2]:
!ls codebench/2016-1/102/users/
# visualizando os alunos de uma turma

1088  1281  1287  1293	1298  1304  1309  1314	1462  1575  1705
1175  1283  1289  1294	1299  1305  1310  1315	1464  1610  1718
1278  1284  1290  1295	1300  1306  1311  1316	1465  1612  1719
1279  1285  1291  1296	1302  1307  1312  1393	1565  1667
1280  1286  1292  1297	1303  1308  1313  1434	1573  1697

In [3]:
!ls codebench/2016-1/102/users/1088/
# visualizando os dados que cada usuário possui

codemirror  codes  executions  grades  logins.log  user.data

In [0]:
!ls codebench/2016-1/102/users/1088/grades/ 
# esse não tem o arquivo de notas

In [5]:
!ls codebench/2016-1/102/users/1281/grades/
# possue os arquivos de nota e log

106.log  136.log  158.log  184.log  199.log  217.log  59.log  97.log
126.log  149.log  173.log  18.log   208.log  44.log   75.log  final_grade.data

In [6]:
!cat codebench/2016-1/102/users/1281/grades/106.log
# visualisando o conteúdo de um arquivo de log, 
# esse aluno fez todos os exercícios

---- grade (0-10): 10
---- number of exercises: 9
---- correct: 9
---- incorrect: 0
---- blank: 0

In [7]:
!cat codebench/2016-1/102/users/1281/grades/final_grade.data
# visualisando o conteúdo de um aquivo de notafinal

8.31

In [8]:
!ls codebench/2016-1/102/users/1287/grades/

126.log  158.log  184.log  199.log  44.log  97.log
149.log  173.log  18.log   217.log  59.log  final_grade.data

In [9]:
!ls codebench/2016-1/102/users/1293/grades/

106.log  136.log  158.log  184.log  199.log  217.log  59.log  97.log
126.log  149.log  173.log  18.log   208.log  44.log   75.log  final_grade.data

In [10]:
!ls codebench/2016-1/102/users/1298/grades/

106.log  136.log  158.log  184.log  199.log  217.log  59.log  97.log
126.log  149.log  173.log  18.log   208.log  44.log   75.log  final_grade.data

In [11]:
!ls codebench/2016-1/102/users/1434/grades/

106.log  136.log  158.log  184.log  199.log  217.log  59.log  97.log
126.log  149.log  173.log  18.log   208.log  44.log   75.log  final_grade.data

## listando os usuários que tenha N arquivos no diretório grades/

In [12]:
import re
import os

root = 'codebench/'

count_one_list = 0
for semester_id in os.listdir(root):
    path_class = os.path.join(root, semester_id)
    for class_id in os.listdir(path_class):
        path_user = os.path.join(path_class, class_id, 'users/')
        for user_id in os.listdir(path_user):
            path_grade = os.path.join(path_user, user_id, 'grades/')
            if len(os.listdir(path_grade)) == 0:
                count_one_list += 1
                print(path_grade, os.listdir(path_grade))
print(count_one_list)

codebench/2018-1/186/users/3153/grades/ []
codebench/2018-1/180/users/2869/grades/ []
codebench/2018-1/181/users/3478/grades/ []
codebench/2018-1/181/users/1770/grades/ []
codebench/2018-1/181/users/2596/grades/ []
codebench/2018-1/189/users/3634/grades/ []
codebench/2018-1/187/users/3147/grades/ []
codebench/2018-1/187/users/3257/grades/ []
codebench/2018-1/187/users/2445/grades/ []
codebench/2018-1/187/users/3153/grades/ []
codebench/2018-1/187/users/2535/grades/ []
codebench/2018-1/185/users/1168/grades/ []
codebench/2016-1/109/users/1295/grades/ []
codebench/2016-1/109/users/1287/grades/ []
codebench/2016-1/109/users/1462/grades/ []
codebench/2016-1/109/users/1183/grades/ []
codebench/2016-1/109/users/1642/grades/ []
codebench/2016-1/109/users/1251/grades/ []
codebench/2016-1/105/users/1171/grades/ []
codebench/2016-1/105/users/1753/grades/ []
codebench/2016-1/105/users/1710/grades/ []
codebench/2016-1/105/users/1693/grades/ []
codebench/2016-1/111/users/1190/grades/ []
codebench/2016-1/111/users/1403/grades/ []
codebench/2016-1/111/users/1248/grades/ []
codebench/2016-1/111/users/1243/grades/ []
codebench/2016-1/111/users/1326/grades/ []
codebench/2016-1/111/users/1194/grades/ []
codebench/2016-1/111/users/1193/grades/ []
codebench/2016-1/111/users/1443/grades/ []
codebench/2016-1/111/users/1189/grades/ []
codebench/2016-1/111/users/1465/grades/ []
codebench/2016-1/111/users/1094/grades/ []
codebench/2016-1/111/users/1306/grades/ []
codebench/2016-1/111/users/1105/grades/ []
codebench/2016-1/111/users/1200/grades/ []
codebench/2016-1/111/users/1197/grades/ []
codebench/2016-1/102/users/1088/grades/ []
codebench/2016-1/102/users/1175/grades/ []
codebench/2016-1/107/users/1643/grades/ []
codebench/2016-1/107/users/1654/grades/ []
codebench/2016-1/107/users/1602/grades/ []
codebench/2016-1/107/users/1169/grades/ []
codebench/2016-1/107/users/1658/grades/ []
codebench/2016-1/107/users/1641/grades/ []
codebench/2016-1/108/users/1390/grades/ []
codebench/2016-1/108/users/1621/grades/ []
codebench/2016-1/108/users/1170/grades/ []
codebench/2016-1/108/users/1615/grades/ []
codebench/2016-1/108/users/1618/grades/ []
codebench/2016-1/108/users/1240/grades/ []
codebench/2016-1/108/users/1251/grades/ []
codebench/2016-1/103/users/1294/grades/ []
codebench/2016-1/103/users/1279/grades/ []
codebench/2016-1/103/users/1610/grades/ []
codebench/2016-1/103/users/1171/grades/ []
codebench/2016-1/103/users/1305/grades/ []
codebench/2016-1/103/users/1295/grades/ []
codebench/2016-1/103/users/1292/grades/ []
codebench/2016-1/103/users/1393/grades/ []
codebench/2016-1/103/users/1293/grades/ []
codebench/2016-1/103/users/1313/grades/ []
codebench/2016-1/103/users/1465/grades/ []
codebench/2016-1/103/users/1306/grades/ []
codebench/2016-1/103/users/1298/grades/ []
codebench/2016-1/103/users/1284/grades/ []
codebench/2016-1/103/users/1641/grades/ []
codebench/2016-1/103/users/1648/grades/ []
codebench/2016-1/110/users/1643/grades/ []
codebench/2016-1/110/users/1223/grades/ []
codebench/2016-1/110/users/1846/grades/ []
codebench/2016-1/106/users/1587/grades/ []
codebench/2016-1/106/users/1585/grades/ []
codebench/2016-1/106/users/1428/grades/ []
codebench/2016-1/106/users/1499/grades/ []
codebench/2019-1/226/users/1407/grades/ []
codebench/2019-1/226/users/1168/grades/ []
codebench/2019-1/226/users/3076/grades/ []
codebench/2019-1/226/users/1064/grades/ []
codebench/2019-1/226/users/1063/grades/ []
codebench/2019-1/226/users/4164/grades/ []
codebench/2019-1/226/users/1062/grades/ []
codebench/2019-1/226/users/1061/grades/ []
codebench/2019-1/223/users/1064/grades/ []
codebench/2019-1/223/users/3263/grades/ []
codebench/2019-1/231/users/1407/grades/ []
codebench/2019-1/231/users/3531/grades/ []
codebench/2019-1/231/users/4605/grades/ []
codebench/2019-1/224/users/3245/grades/ []
codebench/2019-1/230/users/1407/grades/ []
codebench/2019-1/230/users/4029/grades/ []
codebench/2019-1/230/users/4531/grades/ []
codebench/2019-1/221/users/1407/grades/ []
codebench/2019-1/221/users/3677/grades/ []
codebench/2019-1/221/users/1064/grades/ []
codebench/2019-1/221/users/1193/grades/ []
codebench/2019-1/222/users/3034/grades/ []
codebench/2019-1/222/users/2636/grades/ []
codebench/2019-1/225/users/4490/grades/ []
codebench/2019-1/225/users/1956/grades/ []
codebench/2019-1/225/users/1168/grades/ []
codebench/2019-1/225/users/4468/grades/ []
codebench/2019-1/225/users/3777/grades/ []
codebench/2019-1/225/users/3512/grades/ []
codebench/2019-1/220/users/1407/grades/ []
codebench/2019-1/220/users/1860/grades/ []
codebench/2019-1/220/users/4583/grades/ []
codebench/2016-2/125/users/1894/grades/ []
codebench/2016-2/128/users/1909/grades/ []
codebench/2016-2/128/users/1926/grades/ []
codebench/2016-2/124/users/1766/grades/ []
codebench/2017-2/165/users/1860/grades/ []
codebench/2017-2/165/users/2306/grades/ []
codebench/2017-2/165/users/2535/grades/ []
codebench/2017-2/165/users/2914/grades/ []
codebench/2017-2/163/users/2764/grades/ []
codebench/2017-2/163/users/2811/grades/ []
codebench/2017-2/162/users/2872/grades/ []
codebench/2017-2/162/users/2879/grades/ []
codebench/2017-2/162/users/2962/grades/ []
codebench/2017-2/162/users/2763/grades/ []
codebench/2017-2/162/users/2225/grades/ []
codebench/2017-2/162/users/2155/grades/ []
codebench/2017-2/164/users/2010/grades/ []
codebench/2017-2/164/users/2225/grades/ []
codebench/2017-2/164/users/2844/grades/ []
codebench/2017-2/164/users/1770/grades/ []
codebench/2017-1/138/users/1907/grades/ []
codebench/2017-1/138/users/2341/grades/ []
codebench/2017-1/138/users/1925/grades/ []
codebench/2017-1/143/users/2130/grades/ []
codebench/2017-1/141/users/1925/grades/ []
codebench/2017-1/141/users/2531/grades/ []
codebench/2017-1/141/users/2366/grades/ []
codebench/2017-1/139/users/1992/grades/ []
codebench/2017-1/139/users/2479/grades/ []
codebench/2017-1/144/users/1766/grades/ []
codebench/2017-1/144/users/1772/grades/ []
codebench/2017-1/144/users/1925/grades/ []
codebench/2017-1/142/users/2389/grades/ []
codebench/2017-1/137/users/1925/grades/ []
codebench/2017-1/136/users/1986/grades/ []
codebench/2017-1/136/users/2101/grades/ []
codebench/2017-1/135/users/1310/grades/ []
codebench/2017-1/135/users/1305/grades/ []
codebench/2017-1/135/users/2403/grades/ []
codebench/2018-2/204/users/3649/grades/ []
codebench/2018-2/208/users/3873/grades/ []
codebench/2018-2/208/users/3872/grades/ []
codebench/2018-2/208/users/1085/grades/ []
codebench/2018-2/208/users/3947/grades/ []
codebench/2018-2/206/users/3782/grades/ []
codebench/2018-2/207/users/1860/grades/ []
codebench/2018-2/207/users/1198/grades/ []
codebench/2018-2/207/users/3334/grades/ []
codebench/2018-2/207/users/2531/grades/ []
codebench/2018-2/207/users/3836/grades/ []
codebench/2018-2/205/users/3152/grades/ []
codebench/2018-2/205/users/1772/grades/ []
codebench/2018-2/205/users/3821/grades/ []
160

## Critérios de classificação em desistente e não desistente

> "eu considerei desistente todos os alunos que:"
    
    - fizeram menor ou igual a duas listas (TP)
    
    - tem zero em nos 80% últimas Lab

## Adicionado os dados das avaliações

In [0]:
import re
import os

import pandas as pd
import numpy as np


from pprint import pprint

In [0]:
df_assessments = pd.read_csv('/content/drive/My Drive/PBICT-UEA-2019 2020/arquivos_de_mineracao/datasets_csv/dados_de_todos_os_assessmets_com_exercicios.csv')

## Visualizando os titles das avaliações

In [15]:
df_assessments[df_assessments["assessment_type"] == "exam"]["title"].unique()

array(['Trabalho Prático 05: Vetores e Strings',
       'Trabalho Prático 03 - Estrutura Condicional Encadeada',
       'Trabalho Prático 04: Estrutura de Repetição por Condição (while)',
       'Trabalho Prático 06 - Estrutura de Repetição por Contagem (for)',
       'Trabalho Prático 02 - Estrutura Condicional Simples e Composta (sem aninhamento)',
       'Trabalho Prático 07 - Matrizes',
       'Trabalho Prático 1: Variáveis e Estrutura Sequencial de Programação',
       'Prova Final',
       'Trabalho Prático 01: Variáveis e Estrutura Sequencial de Programação',
       'TP 1: Variáveis e Estrutura Sequencial',
       'TP 2 - Condicional Simples e Composta (if/else)',
       'TP 7: Matrizes', 'TP 5: Vetores e Strings',
       'TP 6: Estrutura de Repetição por Contagem (for)',
       'TP 4: Estrutura de Repetição por Condição (while)',
       'TP 3 - Condicionais Encadeadas (if/elif/else)',
       'Trabalho Pratico 7', 'TP 02 – Estrutura Condicional Composta',
       'TP 3 – Condicionais Encadeadas (if/elif)',
       'TP 04: Estrutura de Repetição por Condição (while)',
       'TP01 - Variáveis e Estrutura Sequencial',
       'TP 2 - Condicionais compostos (if/else)',
       'TP 2 - Condicionais simples (if/else)',
       'TP02 - Condicionais simples (if/else)', 'Prova Final - Mateus',
       'TP 06 - Estrutura de Repetição por Contagem (for)',
       'TP03 – Condicionais Encadeadas (if/elif)',
       'TP1 - Variáveis e Estrutura Sequencial',
       'TP. 01 - Variáveis e Estrutura Sequencial',
       'TP. 02 - Condicionais compostos (if/else)',
       'TP 04 - Estrutura de Repetição (while)',
       'TP 03 – Condicionais Encadeadas (if/elif)',
       'TP 02 - Condicionais simples (if/else)',
       'TP 1 - Variáveis e Estrutura Sequencial',
       'Trabalho Prático 07: Matrizes',
       'Trabalho Prático 06 – Repetição por contagem',
       'Trabalho Prático 3: Estruturas Condicionais Encadeadas',
       'Trabalho Prático 4: Estrutura de Repetição por Condição (while)',
       'Trabalho Prático 5: Vetores e Strings',
       'Trabalho Prático 02 - Estrutura Condicional Simples e Composta (OK)',
       'Prova Final - Segunda chamada',
       'Trabalho Prático 07 - Matrizes (Sub)',
       'TP3 - Estrutura Condicional Encadeada', 'TP5: Vetores e Strings',
       'TP1: Variáveis e Estrutura Sequencial',
       'TP4: Estrutura de Repetição por Condição (while)',
       'TP2 - Estrutura Condicional Simples e Composta',
       'TP Substitutivo - EME01', 'TP6: Repetição por contagem',
       'TP7: Matrizes', 'Trabalho Prático 7: Matrizes',
       'TP Substitutivo - EPG01', 'TP: Revisão',
       'Avaliação Parcial 05 – Vetores e Strings',
       'Avaliação Parcial 03 – Estruturas Condicionais Encadeadas',
       'Avaliação Parcial 04 – Estrutura de Repetição por Condição (while)',
       'Avaliação Parcial 06 – Repetição por contagem',
       'Avaliação Parcial 02 – Estrutura Condicional Composta (sem Aninhamento)',
       'Avaliação Parcial 07 – Matrizes',
       'Avaliação 01 - Variáveis e Estrutura Sequencial',
       'Avaliação Parcial 03– Estrutura Condicional Encadeada',
       'Avaliação Parcial 03– Estrutura Condicional Encadeada (turmas de segunda)',
       'Avaliação 01 - Variáveis e Estrutura Sequencial de Programação',
       'Avaliação Parcial 04 – Estrutura de Repetição por Condição (while) - Versão Olímpica :D',
       'Avaliação Parcial 02 [Grupo 2] – Estrutura Condicional Composta (sem Aninhamento)',
       'Trabalho Prático 02 - Estrutura Condicional Simples e Composta',
       'Trabalho Prático Substitutivo',
       'Trabalho Prático 6: Repetição por Contagem'], dtype=object)

In [16]:
df_assessments[df_assessments["assessment_type"] == "homework"]["title"].unique()

array(['Laboratório de Codificação 04 - EXTRA',
       'Laboratório de Codificação 05 – Vetores e Strings',
       'Laboratório de Codificação 04 – Estrutura de Programação de Repetição por Condição',
       'Laboratório de Codificação 02 – Estrutura de Programação Condicional Composta',
       'Laboratório de Codificação 07 – Matrizes',
       'Laboratório 0 – Primeiros passos com o Python',
       'Laboratório de Codificação 06 – Estrutura de Programação de Repetição por Contagem',
       'Laboratório 1 - Variáveis e Estrutura Sequencial de Programação',
       'Laboratório de Codificação 03 – Estrutura de Programação Condicional Encadeada',
       'Laboratório de Codificação 0 – Primeiros passos com o Python',
       'Exercícios de Desafio 4: Estrutura de Programação de Repetição por Condição',
       'Laboratório de Codificação 02 – Estrutura de Programação Condicional',
       'Laboratório de Codificação 01 – Variáveis e Estrutura Sequencial de Programação',
       'Desafios 6 - Repetição por Contagem (for)',
       'Lab 01 – Variáveis e Estrutura Sequencial',
       'Desafios 1 - Variáveis e Estrutura Sequencial',
       'Lab 6 – Repetição por Contagem (for)',
       'Lab 4 – Repetição por Condição (while)', 'Lab 7 – Matrizes',
       'Lab 0 – Primeiros passos com o Python',
       'Lab 3 – Condicionais Encadeados (if/elif)',
       'Lab 2 – Estrutura Condicional Simples', 'Desafio 7 -  Matrizes',
       'Desafios 3 - Condicionais Encadeados (if/elif)',
       'Desafios 5 - Vetores e Strings',
       'Desafios 4 – Repetição por Condição (while)',
       'Desafios 2 - Estruturas Condicionais',
       'Lab 5 – Vetores e Strings',
       'Lab0 – Primeiros passos com o Python',
       'Lab01– Variáveis e Estrutura Sequencial',
       'Lab 1 – Variáveis e Estrutura Sequencial',
       'Lab Codificação 0 – Primeiros passos com o Python',
       'Lab 1 - Variáveis e Estrutura Sequencial',
       'Lab de Codificação 0 – Primeiros passos com Python',
       'Laboratório de Codificação 0 – Primeiros passos',
       'Lab 01 – Variáveis e Est. Seq. de Programação',
       'Lab. de Cod. 0 – Primeiros passos com o Python',
       'LAB 04 – Repetição por Condição',
       'Desafios 04 – Repetição por Condição (while)',
       'LAB 01–Variáveis e Estrutura Sequencial',
       'LAB 0 – Primeiros passos com o Python',
       'LAB 02 – Estrutura Condicional Simples',
       'LAB 05 – Vetores e Strings',
       'LAB 03 – Condicionais Encadeados (if/elif)',
       'Laboratório de Codificação 01',
       'Lab01 – Variáveis e Estrutura Sequencial',
       'Exercícios de Desafio 7: Matrizes',
       'Exercícios de Desafio 2: Estruturas Condicionais Simples e Compostas',
       'Exercícios de Desafio 5: Vetores e Strings',
       'Exercícios de Desafio 3: Estruturas Encadeadas',
       'Exercícios de Desafio 6: Repetição por Contagem',
       'Exercícios de Desafio 1: Variáveis e Estrutura Sequencial de Programação',
       'Desafios 1 - Estrutura Sequencial e Variáveis -19',
       'Lab 0 – Primeiros passos com o Python - 2019',
       'Lab 1 – Estrutura Sequencial e Variáveis - 2019',
       'Desafios 7: Matrizes',
       'Desafios 1 - Estrutura Sequencial e Variáveis 2019',
       'Desafios 7 - Matrizes',
       'Avaliação 01 - Variáveis e Estrutura Sequencial de Programação',
       'Avaliação 1 - Variáveis e Estrutura Sequencial de Programação',
       'Laboratório 2 – Estrutura de Programação Condicional Composta'],
      dtype=object)

## Ordenando as avaliações por data de inicio e retirando o laboratório 0, desafios e avaliações do tipo homework

### Tirando todos desafios, avaliação 01 e avaliação 1

In [0]:
def drop_homeworks(homework_name):
    if not re.search(r'desafio|avaliação\s\d+', homework_name, re.IGNORECASE):
        return True
    else:
        return False

# drop_homeworks('Desafios 7: Matrizes')

In [0]:
filter_homework = df_assessments.apply(lambda row:drop_homeworks(row['title']), axis=1)
df_assessments_2 = df_assessments[filter_homework]

### Removendo o laboratório 0 das turmas

In [0]:
def lab_zero(row_title):
    find_zero = re.search(r'\s0\s|lab0 ', row_title, re.IGNORECASE)
    if find_zero is not None:
        return False
    else:
        return True

In [0]:
filter_homework = df_assessments_2.apply(lambda row: lab_zero(row['title']), axis=1)
df_assessments_2 = df_assessments_2[filter_homework]

### Ordenando cada turma pela data de inicio da avaliação

In [21]:
df_assessments_2 = df_assessments_2.sort_values(by=['class', 'start_date'])
df_assessments_2.head()

    semester  ...                                   exercises_number
770   2016-1  ...  835, 587, 820, 588, 1014, 1015, 825, 1016, 101...
763   2016-1  ...              602, 1053, 820, 1054, 869, 1055, 1056
764   2016-1  ...  1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087...
777   2016-1  ...  1079, 1099, 1100, 1101, 1102, 1103, 1104, 1105...
773   2016-1  ...  1109, 1110, 1111, 1112, 1113, 1114, 1115, 1116...

[5 rows x 10 columns]

### Exportando como csv

In [0]:
df_assessments_2.to_csv('/content/drive/My Drive/PBICT-UEA-2019 2020/arquivos_de_mineracao/datasets_csv/dados_das_avaliacoes_validas.csv', sep=';', index=False)

## Montando um dataset de alunos com notas das avaliações

### Lendo os arquivos e tirando os dados de cada avaliação

In [23]:
def read_grade(path_grade, grade_file):
    grade_path = os.path.join(path_grade, grade_file)
    grade = None
    numb_exercise = None
    correct = None
    incorrect = None
    blank = None
    with open(grade_path, "r") as fl:
        for line in fl.readlines():
            if grade is None: grade = re.search("---- grade \(\d+\-\d+\)\: (.+)", line)
            if numb_exercise is None: numb_exercise = re.search("---- number of exercises: (.+)", line)
            if correct is None: correct = re.search("---- correct: (.+)", line)
            if incorrect is None: incorrect = re.search("---- incorrect: (.+)", line)
            if blank is None: blank = re.search("--- blank: (.+)", line)
        
            if grade is not None and not isinstance(grade, str): grade = grade.group(1)
            if numb_exercise is not None and not isinstance(numb_exercise, str): numb_exercise = numb_exercise.group(1)
            if correct is not None and not isinstance(correct, str): correct = correct.group(1)
            if incorrect is not None and not isinstance(incorrect, str): incorrect = incorrect.group(1)
            if blank is not None and not isinstance(blank, str): blank = blank.group(1)
    return grade, numb_exercise, correct, incorrect, blank

read_grade('codebench/2019-1/230/users/4317/grades/', '1576.log')

('0.625', '16', '1', '0', '15')

### Consultando os dados das avaliações

In [24]:
def consult_type(assessment):
    value = df_assessments[df_assessments['assessment'] == int(assessment)]
    value = value["assessment_type"].values[0]
    return value
consult_type(380)

'exam'

In [25]:
def consult_title(assessment):
    line = df_assessments[df_assessments['assessment'] == int(assessment)]
    value = line['title'].values[0]
    return value
consult_title(380)

'Trabalho Prático 07 - Matrizes'

In [0]:
def amount_homework(class_id):
    return df_assessments[(df_assessments['class'] == int(class_id))  & \
                          (df_assessments['assessment_type'] == 'homework')].count().values[0]

In [0]:
def amount_exam(class_id):
    return df_assessments[(df_assessments['class'] == int(class_id))  & \
                          (df_assessments['assessment_type'] == 'exam')].count().values[0]

### Extraíndo os dados dos alunos em relação as suas avaliações

In [28]:
import re
import os

root = 'codebench/'
features = ['semester_id', 
            'class_id', 
            'user_id', 
            'assessment_id', 
            'grade',
            'amount_exercise',
            'number_of_correct_answers',
            'number_of_incorrects_answers', 
            'number_of_blank_answers',
            'assessment_type',
            'assessment_title',
            'amount_homework',
            'amount_exam'
            ]

df_user_grade = []


cont_p = 0
cont_n = 0

# percorrendo os semestres
for semester_id in os.listdir(root):
    path_class = os.path.join(root, semester_id)

    #percorrendo todas turmas
    for class_id in os.listdir(path_class):
        path_user = os.path.join(path_class, class_id, 'users/')
        
        # quantidade de avaliações do tipo exam
        amount_exam_per_class = amount_exam(class_id)

        #quantidade de avaliações do tipo homework
        amount_homework_per_class = amount_homework(class_id)

        # percorrendo todos os alunos
        for user_id in os.listdir(path_user):
            path_grade = os.path.join(path_user, user_id, 'grades/')
            
            
            # verificando se o aluno fez alguma avaliação
            if len(os.listdir(path_grade)) > 0:
                cont_p += 1
                for assessment_id in os.listdir(path_grade):
                    if 'final' not in assessment_id:
                        
                        # dados das avaliações feitas pelo aluno
                        grade, numb_exercise, correct, incorrect, blank = read_grade(path_grade, assessment_id)
                        assessment_id = assessment_id.replace('.log', '')
                        assess_type = consult_type(assessment_id)
                        assess_title = consult_title(assessment_id)

                        # montando a estrutura com os dados
                        values = [semester_id, class_id, user_id, 
                                    assessment_id, grade, numb_exercise, correct,
                                    incorrect, blank, assess_type, assess_title, 
                                    amount_homework_per_class, amount_exam_per_class]
                        row = dict(zip(features, values))
                        df_user_grade.append(row)
            else:
                cont_n += 1
                values = [semester_id, class_id, user_id, '', '', '', '', '', '', '', '',
                           amount_homework_per_class, amount_exam_per_class]
                row = dict(zip(features, values))
                df_user_grade.append(row)

df_user_grade = pd.DataFrame(df_user_grade)
print(cont_p, cont_n, cont_p+cont_n)

2406 160 2566

In [0]:
df_all_users = df_user_grade[['semester_id','class_id','user_id', 'amount_exam']].groupby(by=['semester_id','class_id','user_id'])['amount_exam'].count().reset_index()
df_all_users.drop('amount_exam', axis=1, inplace=True)

df_user_with_exam = df_user_grade[['semester_id','class_id','user_id', 'assessment_type']]
df_user_with_exam = df_user_with_exam[df_user_with_exam['assessment_type'] == 'exam']
df_user_with_exam = df_user_with_exam.groupby(by=['semester_id','class_id','user_id'])['assessment_type'].count().reset_index()
df_user_with_exam.rename({'assessment_type':'amount_exam'}, axis=1, inplace=True)
# df_user_with_exam.drop('assessment_type', axis=1, inplace=True)

### DataFrame com todos os usuários

In [30]:
df_all_users

     semester_id class_id user_id
0         2016-1      102    1088
1         2016-1      102    1175
2         2016-1      102    1278
3         2016-1      102    1279
4         2016-1      102    1280
...          ...      ...     ...
2561      2019-1      231    4246
2562      2019-1      231    4337
2563      2019-1      231    4339
2564      2019-1      231    4483
2565      2019-1      231    4605

[2566 rows x 3 columns]

### DataFrame com a quantidade de avaliações do tipo *exam* feita por cada usuário

In [31]:
df_user_with_exam

     semester_id class_id user_id  amount_exam
0         2016-1      102    1278            5
1         2016-1      102    1279            2
2         2016-1      102    1280            1
3         2016-1      102    1281            7
4         2016-1      102    1283            7
...          ...      ...     ...          ...
2022      2019-1      231    4245            5
2023      2019-1      231    4246            9
2024      2019-1      231    4337            9
2025      2019-1      231    4339            6
2026      2019-1      231    4483            8

[2027 rows x 4 columns]

### Cruzando os dados de todos os usuário com os usuários que fizeram avaliações

In [32]:
df_amount_exam_by_user = pd.merge(df_all_users, df_user_with_exam, on=['semester_id','class_id','user_id'], how='left')
df_amount_exam_by_user.amount_exam.fillna(0, inplace=True)
df_amount_exam_by_user.amount_exam = df_amount_exam_by_user.amount_exam.astype('int32')
df_amount_exam_by_user

     semester_id class_id user_id  amount_exam
0         2016-1      102    1088            0
1         2016-1      102    1175            0
2         2016-1      102    1278            5
3         2016-1      102    1279            2
4         2016-1      102    1280            1
...          ...      ...     ...          ...
2561      2019-1      231    4246            9
2562      2019-1      231    4337            9
2563      2019-1      231    4339            6
2564      2019-1      231    4483            8
2565      2019-1      231    4605            0

[2566 rows x 4 columns]

## Classificando em 1 se fez mais de 2 assessment do tipo exam ou 0 caso contrário

In [33]:
def two(amount_exam_done):
    if not amount_exam_done <= 2:
        return 1
    else:
        return 0

filtr = df_amount_exam_by_user.apply(lambda row: two(row['amount_exam']), axis=1)
df_amount_exam_by_user['did_more_than_2'] = filtr
df_amount_exam_by_user.drop('amount_exam', axis=1, inplace=True)
df_amount_exam_by_user

     semester_id class_id user_id  did_more_than_2
0         2016-1      102    1088                0
1         2016-1      102    1175                0
2         2016-1      102    1278                1
3         2016-1      102    1279                0
4         2016-1      102    1280                0
...          ...      ...     ...              ...
2561      2019-1      231    4246                1
2562      2019-1      231    4337                1
2563      2019-1      231    4339                1
2564      2019-1      231    4483                1
2565      2019-1      231    4605                0

[2566 rows x 4 columns]

In [34]:
df_amount_exam_by_user.did_more_than_2.value_counts()

1    1670
0     896
Name: did_more_than_2, dtype: int64

## Montando um DataFrame com todos os usuários e todas as avaliações

```bash
codebench
|__ semester
     |___ class
          |--- assessment
          |    |--- x.data
          |    |--- ....
          |    |___ y.data
          |___ user
               |___ grades
                    |--- x.log
                    |--- ....
                    |___ y.log
```

### Selecionando os assessments do tipo homework e não desafios ou seja um laboratório

    *  SE É HOMEWORK E NÃO É UM DESAFIO, GUARDA

In [35]:
df_labs = df_assessments_2[['semester', 'class', 'assessment', 'assessment_type', ]]
df_labs = df_labs[df_labs['assessment_type'] == 'homework']
df_labs.drop('assessment_type', axis=1, inplace=True)
df_labs.rename({'semester':'semester_id', 'class':'class_id', 'assessment':'assessment_id'}, axis=1, inplace=True)
df_labs.reset_index(inplace=True, drop=True)
df_labs

    semester_id  class_id  assessment_id
0        2016-1       102             44
1        2016-1       102             75
2        2016-1       102            106
3        2016-1       102            136
4        2016-1       102            158
..          ...       ...            ...
362      2019-1       231           1689
363      2019-1       231           1719
364      2019-1       231           1769
365      2019-1       231           1810
366      2019-1       231           1852

[367 rows x 3 columns]

### Selecionando as notas de todas as avaliações feitas por cada usuário

In [36]:
df_user_labs = df_user_grade[['semester_id','class_id','user_id', 'assessment_type', 'grade', 'assessment_id']]
df_user_labs = df_user_labs[df_user_labs['assessment_type'] == 'homework']
df_user_labs.drop('assessment_type', axis=1, inplace=True)
df_user_labs.reset_index(inplace=True, drop=True)
df_user_labs

      semester_id class_id user_id    grade assessment_id
0          2018-1      186    1330       10          1035
1          2018-1      186    1330        0          1215
2          2018-1      186    1330  9.16667          1158
3          2018-1      186    1330       10          1246
4          2018-1      186    1330       10          1014
...           ...      ...     ...      ...           ...
18047      2018-2      205    2197       10          1497
18048      2018-2      205    2197       10          1384
18049      2018-2      205    2197       10          1335
18050      2018-2      205    2197       10          1323
18051      2018-2      205    2197       10          1408

[18052 rows x 5 columns]

### Selecionando os laboratórios válidos feitos pelo usuário

In [37]:
labs_id = list(df_labs.assessment_id.values)

def is_valid_lab(assessment_id):
    if assessment_id in labs_id:
        return True
    else:
        return False

filtr = df_user_labs.apply(lambda row: is_valid_lab(int(row['assessment_id'])), axis=1)
df_user_labs = df_user_labs[filtr]
df_user_labs.reset_index(inplace=True, drop=True)
df_user_labs

      semester_id class_id user_id    grade assessment_id
0          2018-1      186    1330       10          1035
1          2018-1      186    1330  9.16667          1158
2          2018-1      186    1330       10          1246
3          2018-1      186    1330       10          1072
4          2018-1      186    1330  6.66667          1120
...           ...      ...     ...      ...           ...
11758      2018-2      205    2197       10          1456
11759      2018-2      205    2197       10          1497
11760      2018-2      205    2197       10          1384
11761      2018-2      205    2197       10          1335
11762      2018-2      205    2197       10          1408

[11763 rows x 5 columns]

### Associando todos os usuário a todos laboratórios válidos

In [38]:
df_all_users.class_id = df_all_users.class_id.astype('int32')
df_labs.class_id = df_labs.class_id.astype('int32')

df_all_users_labs = pd.merge(df_all_users, df_labs, on=['semester_id', 'class_id'], how='left')
df_all_users_labs #.groupby(['semester_id', 'class_id', 'user_id']).count()

      semester_id  class_id user_id  assessment_id
0          2016-1       102    1088             44
1          2016-1       102    1088             75
2          2016-1       102    1088            106
3          2016-1       102    1088            136
4          2016-1       102    1088            158
...           ...       ...     ...            ...
18101      2019-1       231    4605           1689
18102      2019-1       231    4605           1719
18103      2019-1       231    4605           1769
18104      2019-1       231    4605           1810
18105      2019-1       231    4605           1852

[18106 rows x 4 columns]

### Agrupando as notas dos laboratórios a cada usuário e atribuíndo 0 para os que não tem nota na avaliação

In [39]:
# df_user_labs.class_id = df_user_labs.class_id.astype(str)
# df_user_labs.user_id = df_user_labs.user_id.astype(str)
# df_user_labs.assessment_id = df_user_labs.assessment_id.astype(str)

df_all_users_labs.class_id = df_all_users_labs.class_id.astype(str)
# df_all_users_labs.user_id = df_all_users_labs.user_id.astype(str)
df_all_users_labs.assessment_id = df_all_users_labs.assessment_id.astype(str)

df = pd.merge(df_all_users_labs, df_user_labs, on=['semester_id', 'class_id', 'user_id', 'assessment_id'], how='left')
# df.groupby(['semester_id', 'class_id', 'user_id'])['assessment_id'].count().reset_index()
df.grade.fillna(0, inplace=True)
df

      semester_id class_id user_id assessment_id grade
0          2016-1      102    1088            44     0
1          2016-1      102    1088            75     0
2          2016-1      102    1088           106     0
3          2016-1      102    1088           136     0
4          2016-1      102    1088           158     0
...           ...      ...     ...           ...   ...
18101      2019-1      231    4605          1689     0
18102      2019-1      231    4605          1719     0
18103      2019-1      231    4605          1769     0
18104      2019-1      231    4605          1810     0
18105      2019-1      231    4605          1852     0

[18106 rows x 5 columns]

In [0]:
df.to_csv('/content/drive/My Drive/PBICT-UEA-2019 2020/arquivos_de_mineracao/datasets_csv/dados_de_todos_os_usuarios_e_notas_homework.csv')

## Verificando se o aluno fez 80% dos exercícios

In [0]:
def zero_perct(group):
    amount_numbers = group.grade.count()
    count_zero = 0
    for g in group.grade:
        if float(g) == 0.0:
            count_zero += 1
    if amount_numbers * 4 <= count_zero * 5:
        return 0
    else:
        return 1
df_zero_perct = df.groupby(['semester_id', 'class_id', 'user_id']).apply(zero_perct).to_frame().reset_index()

In [42]:
df_zero_perct.rename({0:'less_than_80_percent'}, axis=1, inplace=True)
df_zero_perct

     semester_id class_id user_id  less_than_80_percent
0         2016-1      102    1088                     0
1         2016-1      102    1175                     0
2         2016-1      102    1278                     1
3         2016-1      102    1279                     1
4         2016-1      102    1280                     1
...          ...      ...     ...                   ...
2561      2019-1      231    4246                     1
2562      2019-1      231    4337                     1
2563      2019-1      231    4339                     1
2564      2019-1      231    4483                     1
2565      2019-1      231    4605                     0

[2566 rows x 4 columns]

## Agrupando os dois critérios

In [43]:
df_classes = pd.merge(df_amount_exam_by_user, df_zero_perct)
df_classes

     semester_id class_id user_id  did_more_than_2  less_than_80_percent
0         2016-1      102    1088                0                     0
1         2016-1      102    1175                0                     0
2         2016-1      102    1278                1                     1
3         2016-1      102    1279                0                     1
4         2016-1      102    1280                0                     1
...          ...      ...     ...              ...                   ...
2561      2019-1      231    4246                1                     1
2562      2019-1      231    4337                1                     1
2563      2019-1      231    4339                1                     1
2564      2019-1      231    4483                1                     1
2565      2019-1      231    4605                0                     0

[2566 rows x 5 columns]

## Classificando os registros

In [44]:
def classification(pr_1, pr_2):
    if pr_1 == 1 and pr_2 == 1:
        return 'Não Desistente'
    else:
        return 'Desistente'

df_classes['target'] = df_classes.apply(lambda row: classification(row['did_more_than_2'], row['less_than_80_percent']), axis=1)
df_classes

     semester_id class_id  ... less_than_80_percent          target
0         2016-1      102  ...                    0      Desistente
1         2016-1      102  ...                    0      Desistente
2         2016-1      102  ...                    1  Não Desistente
3         2016-1      102  ...                    1      Desistente
4         2016-1      102  ...                    1      Desistente
...          ...      ...  ...                  ...             ...
2561      2019-1      231  ...                    1  Não Desistente
2562      2019-1      231  ...                    1  Não Desistente
2563      2019-1      231  ...                    1  Não Desistente
2564      2019-1      231  ...                    1  Não Desistente
2565      2019-1      231  ...                    0      Desistente

[2566 rows x 6 columns]

In [45]:
df_classes.target.value_counts()

Não Desistente    1642
Desistente         924
Name: target, dtype: int64

In [0]:
df_classes.to_csv('/content/drive/My Drive/PBICT-UEA-2019 2020/arquivos_de_mineracao/datasets_csv/usuarios_classificados.csv', index=False)